'use strict';
// context.js — 렌더 공용 substrate: 상수·타이포·순수 기하 헬퍼·가변 밴드·파생 메타.
//   makeCtx(DECK, deps)가 ctx 하나를 만든다. primitives/visuals/pages가 여기서 값을 받는다.
//   VT/VH(가변 밴드)는 band 객체에 담는다 — renderBody가 band.VT/VH를 갱신하면 모든 렌더러가 본다.
module.exports = function makeCtx(DECK, deps) {
  const { pres, ASSETS, measure, noteTail, skeleton } = deps;
  const { IN, textW, avail, lineCount } = measure;
  const { FREE, isFree, requiredFields } = skeleton;

    const NN = String(DECK.session.no).padStart(2, '0');   // 파일명·정렬용(아라비아)
    const RN = String(DECK.session.no);                    // 화면 표기용(아라비아, zero-pad 없음)
    const SF = `${RN}. ${DECK.session.title}`;
    const AT = DECK.attribution || `Generated by Claude | Concepts, Requirements and feedback: Youngon Kim`;

    const C = { navy: '1B3A6B', navyLight: 'EBF1F8', white: 'FFFFFF', dark: '2D3748', muted: '6B7280', line: '1B3A6B', lineL: 'CBD5E1', fail: 'FEE2E2', failL: 'DC2626', failT: '991B1B', teal: '007965' };
    const FF = '맑은 고딕';
    const LM = 0.35, CW = 9.30, Y_START = 1.60, Y_LINE = 5.70, Y_BOT = 5.90;
    // 시각화 밴드: 질문/리드 밴드(1.45~2.23) 아래 ~ 하단 구분선 위
    const CTX_TOP = 1.45;              // 질문/리드 밴드 시작
    const VB = 5.66;                   // 시각화 하한(수평선 5.70 위)
    const F_BODY = 14;      // 본문 텍스트(질문/리드/도입)
    const F_IN   = 12;      // box/표 내부 텍스트
    const F_HEAD = 12;      // box/표 제목·헤더 (bold)
    const F_QKO  = 14;      // 인용 한글
    const F_QEN  = 10;      // 인용 영문·저자
    const PAD    = 0.0787;  // 0.2cm = 0.0787in — box/표 상하좌우 내부 여백
    const MG     = 5.67;    // 0.2cm를 pptxgenjs margin(pt) 단위로: 0.2cm ≈ 5.67pt
    const SP     = 3;       // 문장 간 전후 간격 3pt
    const LH     = 0.24;    // 텍스트 1줄 높이 추정(F_IN 기준, in)
    // ── 폭 모델(단일 소스) ─────────────────────────────────────────────────
    // 문자폭 계산은 measure.js 하나만 쓴다. 엔진과 verify가 같은 함수를 공유해야
    // "엔진이 그리는 줄 수 = 검증기가 세는 줄 수"가 성립하고, 오버플로가 구조적으로 사라진다.
    // 이 파일 안에서 문자폭 상수를 다시 정의하지 않는다.
    //   bullet : 불릿 들여쓰기(pt). 불릿이 없는 텍스트는 false를 넘긴다.
    //   fs     : 폰트 크기(pt). 기본은 box/표 본문(12pt).
    const lines = (t, w, bullet = 10, fs = F_IN) => {
        const av = bullet === false ? w - PAD * 2 : avail(w, bullet);
        return String(t).split('\n').reduce((n, par) => n + lineCount(par, av, fs), 0);
    };
    // 글자가 실제로 먹는 높이 = 줄 수 × 줄높이(1.2em) + 문단 수 × 문단간격(전후 3pt) + 상하 여백.
    // 박스 높이는 이 값으로 배정한다. '줄 수 × 0.24' 같은 근사치를 쓰면 문단이 늘어날수록
    // 배정이 모자라 글자가 박스를 벗어난다.
    const lineH = (fs) => IN(fs * 1.2);
    const textH = (ln, paras, fs = F_IN) => ln * lineH(fs) + paras * (2 * SP / 72) + PAD * 2;
    const SLACK = 0.06;                                  // 폰트 대체 오차 흡수용 여유

    // 헤더 폰트는 길이에 따라 분기한다: 22pt로 한 줄에 들어가면 22pt, 아니면 18pt.
    // (헤더 박스 h=0.50 / 구분선 y=0.80이 고정이라 두 줄이 되면 구분선을 침범한다)
    const hdrFS = (t) => (textW(t, 22) <= CW - 0.10 ? 22 : 18);
    const quoteH = (ko, en, author) => {
        const av = CW - PAD * 2;                                   // 중앙 정렬, 불릿 없음
        return Math.max(0.78, lineCount(`\u201C${ko}\u201D`, av, F_QKO) * 0.24
                            + lineCount(`${en} — ${author}`, av, F_QEN) * 0.18 + PAD * 2);
    };
    const F_CAP = 8;                                     // caption(출처·한계) — 원문을 넣으면 길어진다
    const F_ELAB = 10;                                   // 간선 라벨 (선 위에, 배경 없이)
    const F_STMT = 20;                                   // statement 본문 한 문장
    const F_SRC = 10;                                    // statement의 영문 원문·저자
    const F_NUM = 18;                                    // 수치 계열의 숫자
    const CAP_LH = 0.16;                                 // caption 한 줄 높이(8pt)
    const CAP_MAX = 3;                                   // caption 최대 줄 수 — 넘으면 발췌하고 '…'로 줄인다
    const capLines = (t) => Math.min(CAP_MAX, lineCount(String(t), CW - PAD * 2, F_CAP));
    const capH = (t) => t ? capLines(t) * CAP_LH + 0.06 : 0;
    const PAL = [C.navy, C.teal, C.muted, C.lineL];      // 수치 계열 색 순서
    const onDark = (c) => c === C.navy || c === C.teal || c === C.failT;

    const nodesOf = (d) => (d.nodes || []).map(n => ({ ...n, label: String(n.label).replace(/\\n|<br\s*\/?>/gi, '\n') }));
    const edgesOf = (d, ns) => (d.edges && d.edges.length) ? d.edges
                              : ns.slice(1).map((n, i) => ({ from: ns[i].id, to: n.id }));   // 생략 시 순차 체인

    const LOOP_IN = 0.70;                                   // 타원 내접 폭 비율

  const band = { VT: 2.40, VH: VB - 2.40 };   // 원본 316: let VT=2.40, VH=VB-VT. renderBody가 슬라이드마다 갱신.

  return {
    pres, DECK, ASSETS, noteTail, band,
    C, FF, LM, CW, Y_START, Y_LINE, Y_BOT, CTX_TOP, VB,
    F_BODY, F_IN, F_HEAD, F_QKO, F_QEN, PAD, MG, SP, LH, SLACK,
    F_CAP, F_ELAB, F_STMT, F_SRC, F_NUM, CAP_LH, CAP_MAX, LOOP_IN, PAL,
    NN, RN, SF, AT,
    IN, textW, avail, lineCount,
    FREE, isFree, requiredFields,
    lines, lineH, textH, hdrFS, quoteH, capLines, capH, onDark, nodesOf, edgesOf,
  };
};
